import UIKit
import Wailsmobile

@main
class WailsApplication: UIResponder, UIApplicationDelegate {
    var window: UIWindow?
    private var plugins: [String: WailsPlugin] = [:]
    private lazy var nativeCallHandler = NativeCallHandler(appRouter: self)

    func application(_ application: UIApplication,
                     didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        // Start the Go runtime and bind the mobile engine.
        Wailsmobile.startApplication()

        // Register the global native call handler used by the Go side.
        // The exact protocol name is generated by gomobile for `NativeCallHandler`.
        Wailsmobile.setNativeCallHandler(nativeCallHandler)

        // Register your plugin implementations here.
        // registerPlugin(PermissionsPlugin())
        // registerPlugin(FilePickerPlugin())

        window = UIWindow(frame: UIScreen.main.bounds)
        window?.rootViewController = WailsWebViewController()
        window?.makeKeyAndVisible()

        return true
    }

    private func registerPlugin(_ plugin: WailsPlugin) {
        plugins[plugin.domain] = plugin
        if let rootController = window?.rootViewController {
            plugin.onAttach(rootController)
        }
    }

    func plugin(for domain: String) -> WailsPlugin? {
        return plugins[domain]
    }
}

private final class NativeCallHandler: NSObject {
    private weak var appRouter: WailsApplication?

    init(appRouter: WailsApplication) {
        self.appRouter = appRouter
    }

    // This method should match the gomobile-generated native handler entrypoint.
    // If the generated iOS binding uses a different selector name, adjust it accordingly.
    @objc func onNativeCall(_ method: String, args: String) -> String {
        let parts = method.split(separator: ":", maxSplits: 1, omittingEmptySubsequences: false)
        guard parts.count == 2,
              let plugin = appRouter?.plugin(for: String(parts[0])) else {
            return "{\"error\":\"Plugin domain not found\"}"
        }

        return plugin.handleAction(String(parts[1]), jsonArgsPayload: args)
    }
}
